POST http://localhost:4002/products
content-type: application/json

{
    "name": "Tesoura",
    "price": 10
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/0db26ac9-170c-46a1-934c-b61fdb690760

###

PUT http://localhost:4002/products/fa441f22-befd-4e9a-8c59-be08b07b549e
content-type: application/json

{
    "name": "Caneta azul",
    "price": 3
}

###

DELETE http://localhost:4002/products/0cea7d5d-97b1-4a5d-9da8-61616d7ddbb9